### ISSUE TITLE
ATLResourceBundle bundleNotFound

### ISSUE THREAD

**Issue by mathmatrix828** [mathmatrix828/Atlas-iOS#1]
ATLResouceBundle is returning nil because the bundle org.cocoapods.Atlas is not found - suggests not exists?

Also, why load a UIImage in ATLConversationViewCell instead of loading as a font like FontAwesome?

**Comment by mathmatrix828** [comment]
@feifanzhou I'd love it if you'd drop your insight on this

**Comment by mathmatrix828** [comment]
It looks like the resources are not being copied by Cocoapods. Investigating

**Comment by feifanzhou** [comment]
We pushed some changes on Friday to support Carthage … if you want to isolate, point your CocoaPods to `bffddc823f3d83afa4655b327cc70d137563c31a` (https://github.com/layerhq/Atlas-iOS/commit/bffddc823f3d83afa4655b327cc70d137563c31a). Didn't catch this issue with CocoaPods 0.39 though

**Comment by mathmatrix828** [comment]
Looks like everything has been resolved

**Comment by feifanzhou** [comment]
What was the ultimate resolution?

**Comment by mathmatrix828** [comment]
Updated Podfile as per https://github.com/layerhq/Atlas-iOS/pull/1187. Pod dependancies were not being injected properly (or any dependency, including libs) due to outdated Podfile

**Comment by feifanzhou** [comment]
Awesome, will review shortly. Thanks for investigating so far! 💯
